const { test, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { harness, load } = require('./harness.cjs');
const results = [];
function scenario(id, group, title, rule, expected, fn, severity = 'Média') {
  test(`${id} ${title}`, { concurrency: false }, async () => {
    const h = harness(); const start = performance.now(); const record = { id, group, title, rule, expected, severity, status: 'Aprovado', actual: '', durationMs: 0 };
    try { record.actual = (await fn(h)) || 'Asserções atendidas.'; }
    catch (error) { record.status = 'Falhou'; record.actual = error.message.slice(0, 1100); throw error; }
    finally { record.durationMs = Math.round((performance.now() - start) * 100) / 100; results.push(record); h.close(); }
  });
}
const status = (r, code) => assert.equal(r.status, code, `HTTP recebido ${r.status}; esperado ${code}`);
const count = h => h.sqlite.prepare('SELECT COUNT(*) n FROM orders').get().n;

scenario('U01','Unitário','Perfil válido e remoção de espaços','Nome 3–100; CPF 11; telefone 10–11; CEP 8; endereço 10–250; cartão permitido.','Perfil aceito e nome normalizado.',async h=>{assert.equal(h.units.profileSchema.parse({...h.profile,name:'  Pessoa Teste  '}).name,'Pessoa Teste');});
for (const [id,field,value] of [['U02','cpf','123'],['U03','phone','119'],['U04','cep','abc'],['U05','card','9999'],['U06','name','ab'],['U07','address','x'.repeat(251)]])
  scenario(id,'Unitário',`Rejeitar ${field} fora da regra`,`Validar tipo, formato e limites de ${field}.`,'Validação recusa a entrada.',async h=>{assert.equal(h.units.profileSchema.safeParse({...h.profile,[field]:value}).success,false);});
scenario('U08','Unitário','Rejeitar campo extra de perfil','Objeto estrito não permite campo role.','role=admin rejeitado.',async h=>{assert.equal(h.units.profileSchema.safeParse({...h.profile,role:'admin'}).success,false);},'Alta');
scenario('U09','Unitário','Limites mínimo e máximo de produto','Preço inteiro 100–10000000 centavos; estoque inteiro 0–10000.','Valores nos extremos são aceitos.',async h=>{for(const p of [100,10000000])for(const s of [0,10000])assert.ok(h.units.productSchema.safeParse({...h.product,price:p,stock:s}).success);});
for(const [id,field,value] of [['U10','price',99],['U11','price',10000001],['U12','price',100.5],['U13','stock',-1],['U14','stock',1.5],['U15','category','Outra']])
  scenario(id,'Unitário',`Rejeitar ${field}=${value}`,'Preço/estoque inteiros e categoria na lista permitida.','Valor inválido rejeitado.',async h=>{assert.equal(h.units.productSchema.safeParse({...h.product,[field]:value}).success,false);});
scenario('U16','Unitário','Criptografia reversível com Unicode','AES-GCM preserva texto quando chave e proprietário coincidem.','Texto descriptografado idêntico.',async h=>{const v='José, São Paulo, cartão ••••';assert.equal(await h.units.crypt(await h.units.crypt(v,'alice'),'alice',true),v);},'Alta');
scenario('U17','Unitário','IV aleatório','Criptografar duas vezes o mesmo texto produz ciphertext diferente.','Ciphertexts distintos.',async h=>{assert.notEqual(await h.units.crypt('test','alice'),await h.units.crypt('test','alice'));},'Alta');
scenario('U18','Unitário','Proprietário incorreto não descriptografa','Additional authenticated data vincula ciphertext ao dono.','Descriptografia rejeitada.',async h=>{await assert.rejects(()=>h.units.crypt('', 'bob',true));const v=await h.units.crypt('test','alice');await assert.rejects(()=>h.units.crypt(v,'bob',true));},'Alta');
scenario('U19','Unitário','Ciphertext adulterado','GCM deve detectar alteração do payload.','Falha de integridade.',async h=>{const v=await h.units.crypt('test','alice');const b=Buffer.from(v,'base64');b[b.length-1]^=1;await assert.rejects(()=>h.units.crypt(b.toString('base64'),'alice',true));},'Alta');
scenario('U20','Unitário','Redirecionamento de login restrito à origem','Não aceitar return_to externo, // ou rotas reservadas.','Destino externo substituído por /.',async()=>{const a=load('app/chatgpt-auth.ts',{'next/headers':{headers:async()=>new Headers()},'next/navigation':{redirect:()=>{}}});for(const v of ['https://evil.test','//evil.test','/callback','/signin-with-chatgpt'])assert.equal(a.chatGPTSignInPath(v),'/signin-with-chatgpt?return_to=%2F');assert.equal(a.chatGPTSignInPath('/?tab=conta'),'/signin-with-chatgpt?return_to=%2F%3Ftab%3Dconta');},'Alta');

scenario('F01','Funcional','Listar catálogo autenticado','GET deve retornar catálogo e apenas dados próprios.','HTTP 200 e seis produtos demonstrativos.',async h=>{status(await h.api.GET(),200);assert.equal((await h.json()).products.length,6);});
scenario('F02','Funcional','Criar, ler e atualizar perfil','Salvar perfil por identidade autenticada.','Atualização substitui o perfil e leitura reproduz os dados.',async h=>{status(await h.saveProfile(),200);status(await h.post({action:'profile',data:{...h.profile,name:'Outro Nome'}}),200);assert.equal((await h.json()).profile.name,'Outro Nome');assert.equal(h.sqlite.prepare('SELECT COUNT(*) n FROM profiles').get().n,1);});
scenario('F03','Funcional','Excluir perfil','Excluir somente perfil da identidade atual.','Perfil ausente na leitura.',async h=>{await h.saveProfile();status(await h.post({action:'delete-profile'}),200);assert.equal((await h.json()).profile,null);});
scenario('F04','Funcional','Criar produto','Persistir descrição, preço, categoria e estoque.','Produto aparece no catálogo.',async h=>{const id=await h.createProduct();assert.equal((await h.json()).products.find(p=>p.id===id).stock,3);});
scenario('F05','Funcional','Atualizar produto próprio','Somente dono altera; preço e estoque atualizados.','Mudanças persistidas.',async h=>{const id=await h.createProduct();status(await h.post({action:'product',id,data:{...h.product,price:23000,stock:7}}),200);assert.equal((await h.json()).products.find(p=>p.id===id).price,23000);});
scenario('F06','Funcional','Retirar produto','Soft delete preserva histórico e oculta produto de outros usuários.','Produto inativo; outro usuário não o vê.',async h=>{const id=await h.createProduct();status(await h.post({action:'delete-product',id}),200);assert.equal(h.sqlite.prepare('SELECT active FROM products WHERE id=?').get(id).active,0);h.user('bob');assert.equal((await h.json()).products.some(p=>p.id===id),false);});
scenario('F07','Funcional','Comprar produto de vendedor','Quantidade vezes preço mais 1990 centavos de frete por linha.','Total 21990; estoque de 3 para 1; status Confirmado.',async h=>{const id=await h.createProduct();h.user('bob');await h.saveProfile();status(await h.checkout(id,2),200);const o=h.sqlite.prepare('SELECT * FROM orders').get();assert.equal(o.total,21990);assert.equal(o.status,'Confirmado');assert.equal(h.sqlite.prepare('SELECT stock FROM products').get().stock,1);});
scenario('F08','Funcional','Carrinho com dois produtos','Frete fixo cobrado por linha, preço obtido no servidor.','Dois pedidos; total agregado 31980 centavos.',async h=>{const a=await h.createProduct();const b=await h.createProduct({...h.product,price:18000});await h.saveProfile();status(await h.post({action:'checkout',nonce:crypto.randomUUID(),items:[{id:a,qty:1},{id:b,qty:1}]}),200);assert.equal(count(h),2);assert.equal(h.sqlite.prepare('SELECT SUM(total) n FROM orders').get().n,31980);});
scenario('F09','Funcional','Compra de produto demonstrativo','Catálogo embutido permite checkout simulado.','Pedido criado para demo-1; estoque ilustrativo permanece 18.',async h=>{await h.saveProfile();status(await h.checkout('demo-1'),200);assert.equal(count(h),1);assert.equal((await h.json()).products.find(p=>p.id==='demo-1').stock,18);});
scenario('F10','Funcional','Avançar entrega em sequência','Confirmado → Em preparação → Em transporte → Entregue.','Três avanços e bloqueio de um quarto.',async h=>{const id=await h.createProduct();await h.saveProfile();await h.checkout(id);const o=h.sqlite.prepare('SELECT id FROM orders').get().id;for(const stage of ['Em preparação','Em transporte','Entregue']){status(await h.post({action:'status',id:o}),200);assert.equal(h.sqlite.prepare('SELECT status FROM orders').get().status,stage);}status(await h.post({action:'status',id:o}),400);});
scenario('F11','Funcional','Snapshot de entrega não muda com perfil','Pedido preserva endereço do momento da compra.','Endereço antigo no pedido e novo no perfil.',async h=>{const id=await h.createProduct();await h.saveProfile();await h.checkout(id);await h.post({action:'profile',data:{...h.profile,address:'Rua Nova de Teste, 50'}});const d=await h.json();assert.equal(d.orders[0].deliveryAddress,h.profile.address);assert.equal(d.profile.address,'Rua Nova de Teste, 50');});
scenario('F12','Funcional','Preservar pedido após exclusão de perfil','Retenção do snapshot de pedido é independente do perfil.','Pedido e entrega permanecem legíveis.',async h=>{const id=await h.createProduct();await h.saveProfile();await h.checkout(id);await h.post({action:'delete-profile'});assert.equal((await h.json()).orders[0].deliveryAddress,h.profile.address);});
scenario('F13','Funcional','Repetição idêntica não duplica pedido','Mesmo comprador e nonce devem ser idempotentes.','Um pedido e uma única baixa de estoque.',async h=>{const id=await h.createProduct();await h.saveProfile();const n=crypto.randomUUID();status(await h.checkout(id,1,n),200);status(await h.checkout(id,1,n),200);assert.equal(count(h),1);assert.equal(h.sqlite.prepare('SELECT stock FROM products').get().stock,2);});

scenario('S01','Segurança funcional','Bloquear GET sem login','Negar leitura sem identidade.','HTTP 401.',async h=>{h.user(null);status(await h.api.GET(),401);},'Alta');
scenario('S02','Segurança funcional','Bloquear todas as mutações sem login','Perfil/produto/checkout/status/exclusões exigem identidade.','Todas retornam 401.',async h=>{h.user(null);for(const action of ['profile','product','checkout','status','delete-profile','delete-product'])status(await h.post({action}),401);},'Alta');
scenario('S03','Segurança funcional','CSRF com origem externa','Origem de mutação deve coincidir exatamente com a do endpoint.','HTTP 403.',async h=>{status(await h.post({action:'delete-profile'},{headers:{Origin:'https://evil.test'}}),403);},'Alta');
scenario('S04','Segurança funcional','CSRF sem cabeçalho obrigatório','Requisição sem X-Vitrine-Request não pode alterar estado.','HTTP 403.',async h=>{status(await h.post({action:'delete-profile'},{headers:{'X-Vitrine-Request':null}}),403);},'Alta');
scenario('S05','Segurança funcional','CSRF sem origem','Ausência de Origin não permite mutação.','HTTP 403.',async h=>{status(await h.post({action:'delete-profile'},{headers:{Origin:null}}),403);},'Alta');
scenario('S06','Segurança funcional','IDOR na alteração de produto','Um usuário não altera produto de outro.','HTTP 404 e preço intacto.',async h=>{const id=await h.createProduct();h.user('bob');status(await h.post({action:'product',id,data:{...h.product,price:1e5}}),404);assert.equal(h.sqlite.prepare('SELECT price FROM products').get().price,10000);},'Alta');
scenario('S07','Segurança funcional','IDOR na retirada de produto','Somente dono pode desativar.','HTTP 404; active=1.',async h=>{const id=await h.createProduct();h.user('bob');status(await h.post({action:'delete-product',id}),404);assert.equal(h.sqlite.prepare('SELECT active FROM products').get().active,1);},'Alta');
scenario('S08','Segurança funcional','Isolar perfis entre usuários','Identidade enviada no body não concede acesso a outro perfil.','Perfil de Alice preservado e Bob só lê o próprio.',async h=>{await h.saveProfile();h.user('bob');assert.equal((await h.json()).profile,null);status(await h.post({action:'profile',owner:'alice',data:{...h.profile,name:'Perfil de Bob'}}),200);h.user('alice');assert.equal((await h.json()).profile.name,h.profile.name);},'Alta');
scenario('S09','Segurança funcional','Isolar pedidos de terceiros','Somente comprador e vendedor veem pedido e endereço.','Terceiro recebe lista vazia.',async h=>{const id=await h.createProduct();h.user('bob');await h.saveProfile();await h.checkout(id);h.user('charlie');assert.equal((await h.json()).orders.length,0);},'Alta');
scenario('S10','Segurança funcional','Vendedor recebe dados mínimos de entrega','Não revelar CPF, cartão ou telefone pelo endpoint de pedidos.','Apenas nome, endereço e CEP; perfil do comprador indisponível.',async h=>{const id=await h.createProduct();h.user('bob');await h.saveProfile();await h.checkout(id);h.user('alice');const d=await h.json();assert.equal(d.profile,null);assert.equal(d.orders[0].deliveryAddress,h.profile.address);for(const k of ['cpf','phone','card','delivery'])assert.equal(k in d.orders[0],false);},'Alta');
scenario('S11','Segurança funcional','Comprador não altera entrega','Só o vendedor avança o status.','HTTP 400; estado intacto.',async h=>{const id=await h.createProduct();h.user('bob');await h.saveProfile();await h.checkout(id);const o=h.sqlite.prepare('SELECT id FROM orders').get().id;status(await h.post({action:'status',id:o}),400);},'Alta');
scenario('S12','Segurança funcional','Ignorar preço adulterado no checkout','Preço e frete não podem vir do navegador.','Valor armazenado 11990 apesar de price=1 e total=1.',async h=>{const id=await h.createProduct();await h.saveProfile();status(await h.post({action:'checkout',nonce:crypto.randomUUID(),items:[{id,qty:1}],price:1,total:1,shipping:0}),200);assert.equal(h.sqlite.prepare('SELECT total FROM orders').get().total,11990);},'Alta');
scenario('S13','Segurança funcional','SQL injection é tratada como texto','Consultas parametrizadas não executam payload no nome.','Tabela intacta e nome literal.',async h=>{const payload="Teste'); DROP TABLE profiles; --";const id=await h.createProduct({...h.product,name:payload});assert.equal(h.sqlite.prepare('SELECT name FROM products WHERE id=?').get(id).name,payload);assert.equal(h.sqlite.prepare('SELECT COUNT(*) n FROM profiles').get().n,0);},'Alta');
scenario('S14','Segurança funcional','Payload XSS no servidor permanece JSON','Servidor não interpreta HTML no campo nome.','JSON válido e application/json; execução no navegador não avaliada.',async h=>{const payload='<img src=x onerror=alert(1)>';const id=await h.createProduct({...h.product,name:payload});const r=await h.api.GET();assert.match(r.headers.get('Content-Type'),/application\/json/);assert.equal((await r.json()).products.find(p=>p.id===id).name,payload);},'Alta');
scenario('S15','Segurança funcional','Perfil e entrega criptografados em repouso','Não armazenar campos pessoais em texto claro.','CPF e endereço ausentes nos ciphertexts.',async h=>{const id=await h.createProduct();await h.saveProfile();await h.checkout(id);for(const row of [h.sqlite.prepare('SELECT data c FROM profiles').get(),h.sqlite.prepare('SELECT delivery c FROM orders').get()]){assert.ok(!row.c.includes(h.profile.cpf));assert.ok(!row.c.includes(h.profile.address));}},'Alta');
scenario('S16','Segurança funcional','Cabeçalhos de resposta privada','Respostas API usam no-store, nosniff e same-origin.','Cabeçalhos presentes inclusive em erros.',async h=>{for(const r of [await h.api.GET(),await h.post({action:'unknown'})]){assert.equal(r.headers.get('Cache-Control'),'no-store');assert.equal(r.headers.get('X-Content-Type-Options'),'nosniff');assert.equal(r.headers.get('Referrer-Policy'),'same-origin');}},'Média');
scenario('S17','Segurança funcional','Rate limit por identidade','Máximo 40 mutações por minuto e usuário.','41ª retorna 429; outro usuário pode operar.',async h=>{for(let i=0;i<40;i++)status(await h.post({action:'delete-profile'}),200);status(await h.post({action:'delete-profile'}),429);h.user('bob');status(await h.post({action:'delete-profile'}),200);},'Alta');
scenario('S18','Segurança funcional','Rollback de checkout com estoque esgotado antes do batch','Revalidar estoque dentro da transação e não criar pedidos parciais.','Checkout falha; zero pedidos; primeiro produto não tem baixa parcial.',async h=>{const a=await h.createProduct();const b=await h.createProduct();await h.saveProfile();h.state.beforeBatch=db=>db.prepare('UPDATE products SET stock=0 WHERE id=?').run(b);const r=await h.post({action:'checkout',nonce:crypto.randomUUID(),items:[{id:a,qty:1},{id:b,qty:1}]});assert.notEqual(r.status,200);assert.equal(count(h),0);assert.equal(h.sqlite.prepare('SELECT stock FROM products WHERE id=?').get(a).stock,3);},'Alta');

scenario('E01','Segurança de erro','JSON malformado','Não expor stack ou detalhes internos.','HTTP 400 com mensagem genérica.',async h=>{const r=await h.post(null,{raw:'{broken'});status(r,400);assert.doesNotMatch(await r.text(),/SyntaxError|stack|route\.ts/);});
scenario('E02','Segurança de erro','Content-Type incompatível','Aceitar somente JSON.','text/plain retorna 415.',async h=>{status(await h.post({action:'delete-profile'},{headers:{'Content-Type':'text/plain'}}),415);});
scenario('E03','Segurança de erro','Corpo maior que limite de caracteres','Texto acima de 10000 caracteres deve ser rejeitado.','HTTP 413.',async h=>{status(await h.post(null,{raw:JSON.stringify({x:'a'.repeat(10000)})}),413);});
scenario('E04','Segurança de erro','Checkout sem perfil','Requerer endereço antes de comprar.','HTTP 400; zero pedidos.',async h=>{status(await h.checkout('demo-1'),400);assert.equal(count(h),0);});
scenario('E05','Segurança de erro','Quantidade zero, negativa, fracionária ou acima de 10','Quantidade inteira entre 1 e 10.','Todos retornam 400.',async h=>{await h.saveProfile();for(const qty of [0,-1,1.2,11])status(await h.checkout('demo-1',qty),400);});
scenario('E06','Segurança de erro','Itens duplicados','Uma única linha para cada ID no carrinho.','HTTP 400.',async h=>{await h.saveProfile();status(await h.post({action:'checkout',nonce:crypto.randomUUID(),items:[{id:'demo-1',qty:1},{id:'demo-1',qty:1}]}),400);});
scenario('E07','Segurança de erro','Carrinho vazio ou acima de 20 linhas','Array entre 1 e 20 itens.','HTTP 400.',async h=>{await h.saveProfile();for(const items of [[],Array.from({length:21},(_,i)=>({id:'id'+i,qty:1}))])status(await h.post({action:'checkout',nonce:crypto.randomUUID(),items}),400);});
scenario('E08','Segurança de erro','UUID inválido','IDs de mutação e nonce devem ser UUID.','HTTP 400.',async h=>{status(await h.post({action:'delete-product',id:'not-a-uuid'}),400);status(await h.post({action:'checkout',nonce:'bad',items:[{id:'demo-1',qty:1}]}),400);});
scenario('E09','Segurança de erro','Produto inexistente ou retirado','Não vender produto fora do catálogo ativo.','HTTP 409; nenhum pedido.',async h=>{const id=await h.createProduct();await h.post({action:'delete-product',id});await h.saveProfile();status(await h.checkout(id),409);status(await h.checkout(crypto.randomUUID()),409);assert.equal(count(h),0);});
scenario('E10','Segurança de erro','Estoque insuficiente','Quantidade não pode superar estoque real.','HTTP 409; estoque intacto.',async h=>{const id=await h.createProduct();await h.saveProfile();status(await h.checkout(id,4),409);assert.equal(h.sqlite.prepare('SELECT stock FROM products').get().stock,3);});
scenario('E11','Segurança de erro','Ação desconhecida','Negar ações fora da lista.','HTTP 400.',async h=>{status(await h.post({action:'admin-override'}),400);});
scenario('E12','Segurança de erro','Falha de leitura no banco','Não expor detalhes da conexão.','HTTP 503 com mensagem genérica.',async h=>{h.state.failDB=true;const r=await h.api.GET();status(r,503);assert.doesNotMatch(await r.text(),/password|SECRET|SQL/);},'Alta');
scenario('E13','Segurança de erro','Ciphertext corrompido não é retornado','Falha de integridade deve bloquear leitura.','HTTP 503; nenhuma informação pessoal.',async h=>{await h.saveProfile();h.sqlite.prepare('UPDATE profiles SET data=?').run('not-valid');const r=await h.api.GET();status(r,503);assert.doesNotMatch(await r.text(),/12345678900/);},'Alta');
// Additional proposed hardening rules: failures deliberately remain visible; no production code is patched.
scenario('E14','Segurança de erro','Rejeitar MIME application/jsonp','Tipo de mídia deve coincidir com application/json, com parâmetros opcionais.','HTTP 415.',async h=>{status(await h.post({action:'delete-profile'},{headers:{'Content-Type':'application/jsonp'}}),415);},'Baixa');
scenario('E15','Segurança de erro','Limitar corpo por bytes UTF-8','Limite proposto: 10000 bytes antes de processar o JSON.','HTTP 413 para texto Unicode com mais de 10000 bytes.',async h=>{const raw=JSON.stringify({x:'á'.repeat(6000)});assert.ok(Buffer.byteLength(raw)>10000);status(await h.post(null,{raw}),413);},'Média');
scenario('E16','Segurança de erro','Distinguir indisponibilidade de erro de entrada','Falha interna de escrita não deve ser classificada como erro do cliente.','HTTP 503 ou 500.',async h=>{h.state.failDB=true;const r=await h.post({action:'delete-profile'});assert.ok([500,503].includes(r.status),`HTTP recebido ${r.status}; esperado 500 ou 503`);},'Média');
scenario('E17','Segurança de erro','Nonce reutilizado com carrinho diferente','Idempotência deve comparar payload e rejeitar reaproveitamento diferente.','HTTP 409 na segunda compra diferente; pedido original intacto.',async h=>{const id=await h.createProduct();await h.saveProfile();const nonce=crypto.randomUUID();await h.checkout(id,1,nonce);status(await h.checkout(id,2,nonce),409);assert.equal(count(h),1);},'Média');
scenario('E18','Segurança de erro','Chave ausente deve indicar indisponibilidade','Sem segredo de criptografia: não salvar perfil e devolver 5xx.','HTTP 503 ou 500; zero perfis.',async h=>{delete h.env.DATA_KEY;const r=await h.saveProfile();assert.equal(h.sqlite.prepare('SELECT COUNT(*) n FROM profiles').get().n,0);assert.ok([500,503].includes(r.status),`HTTP recebido ${r.status}; esperado 500 ou 503`);},'Média');

after(()=>{
  const report = { executedAt: new Date().toISOString(), node: process.version,
    sourceCommit: '5e80a14406739b390648862c3b2224fd9eafd48c',
    environment: 'Handlers reais executados em Node, identidade/gateway simulados, SQLite em memória com adapter de D1. Sem requisições de escrita na loja publicada.',
    limits: ['Sem cobertura percentual instrumentada.', 'Sem browser E2E, DAST ou pentest.', 'Interleaving de estoque simulado; sem teste multi-isolate Cloudflare.', 'Login externo e cookies da plataforma não exercitados.'],
    counts: { total: results.length, passed: results.filter(r=>r.status==='Aprovado').length, failed: results.filter(r=>r.status==='Falhou').length }, results };
  const output=process.env.TEST_REPORT_PATH || path.resolve(__dirname,'../reports/server-tests.json');
  fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');
  console.log(`Report: ${report.counts.passed}/${report.counts.total} passed, ${report.counts.failed} failed`);
});
